import { PageParam, PageResult } from '@/constants';

export interface OnlineOrderPageParam extends PageParam {
  likeOrderNum: string;
}

export interface OnlineOrderPageResult extends PageResult {
  records: Array<OnlineOrderResult>;
}

export interface OnlineOrderResult {
  id: string;
  orderNum: string;
  actualMerchantRevenue: number;
  orderStatus: string;
  afterSalesStatus: string;
  orderCompletionTime: Date;
}

export enum ORDER_STATUS {
  PENDING_SHIPMENT = 'PENDING_SHIPMENT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  NOT_SHIPPED_REFUND_SUCCESS = 'NOT_SHIPPED_REFUND_SUCCESS',
  SHIPPED_PENDING_RECEIPT = 'SHIPPED_PENDING_RECEIPT',
  SHIPPED_REFUND_SUCCESS = 'SHIPPED_REFUND_SUCCESS',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}

export const ORDER_STATUS_LABEL = {
  PENDING_SHIPMENT: '待发货',
  PENDING_PAYMENT: '待支付',
  NOT_SHIPPED_REFUND_SUCCESS: '未发货，退款成功',
  SHIPPED_PENDING_RECEIPT: '已发货，待签收',
  SHIPPED_REFUND_SUCCESS: '已发货，退款成功',
  RECEIVED: '已签收',
  CANCELLED: '已取消',
};

export const ORDER_STATUS_OPTIONS = [
  { label: ORDER_STATUS_LABEL.PENDING_SHIPMENT, value: ORDER_STATUS.PENDING_SHIPMENT },
  { label: ORDER_STATUS_LABEL.PENDING_PAYMENT, value: ORDER_STATUS.PENDING_PAYMENT },
  { label: ORDER_STATUS_LABEL.NOT_SHIPPED_REFUND_SUCCESS, value: ORDER_STATUS.NOT_SHIPPED_REFUND_SUCCESS },
  { label: ORDER_STATUS_LABEL.SHIPPED_PENDING_RECEIPT, value: ORDER_STATUS.SHIPPED_PENDING_RECEIPT },
  { label: ORDER_STATUS_LABEL.SHIPPED_REFUND_SUCCESS, value: ORDER_STATUS.SHIPPED_REFUND_SUCCESS },
  { label: ORDER_STATUS_LABEL.RECEIVED, value: ORDER_STATUS.RECEIVED },
  { label: ORDER_STATUS_LABEL.CANCELLED, value: ORDER_STATUS.CANCELLED },
];

export enum AFTER_SALES_STATUS {
  PROCESSING = 'PROCESSING',
  REFUND_SUCCESS = 'REFUND_SUCCESS',
  NO_AFTER_SALES_OR_CANCELLED = 'NO_AFTER_SALES_OR_CANCELLED',
}

export const AFTER_SALES_STATUS_LABEL = {
  PROCESSING: '售后处理中',
  REFUND_SUCCESS: '退款成功',
  NO_AFTER_SALES_OR_CANCELLED: '无售后或售后取消',
};

export const AFTER_SALES_STATUS_OPTIONS = [
  { label: AFTER_SALES_STATUS_LABEL.PROCESSING, value: AFTER_SALES_STATUS.PROCESSING },
  { label: AFTER_SALES_STATUS_LABEL.REFUND_SUCCESS, value: AFTER_SALES_STATUS.REFUND_SUCCESS },
  {
    label: AFTER_SALES_STATUS_LABEL.NO_AFTER_SALES_OR_CANCELLED,
    value: AFTER_SALES_STATUS.NO_AFTER_SALES_OR_CANCELLED,
  },
];
